dateModified: 1585613895
email:
  fromEmail: codingwithkyle@gmail.com
  fromName: Boilerplate
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  23e4e445-4b38-4cb2-b804-8f0709fc5994:
    name: Character
  fcc29f23-916c-4883-90ae-60e9e6f0b466:
    name: Common
fields:
  224fd7cd-0613-42ac-8082-1700a37171a4:
    contentColumnType: integer(10)
    fieldGroup: 23e4e445-4b38-4cb2-b804-8f0709fc5994
    handle: wisdom
    instructions: ''
    name: Wisdom
    searchable: true
    settings:
      decimals: 0
      defaultValue: '0'
      max: null
      min: '0'
      prefix: ''
      size: null
      suffix: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  28c16db0-e3bc-43e3-abda-655cb84246f5:
    contentColumnType: integer(10)
    fieldGroup: 23e4e445-4b38-4cb2-b804-8f0709fc5994
    handle: intelligence
    instructions: ''
    name: Intelligence
    searchable: true
    settings:
      decimals: 0
      defaultValue: '0'
      max: null
      min: '0'
      prefix: ''
      size: null
      suffix: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  43da4518-b607-4804-a699-523220069c18:
    contentColumnType: integer(10)
    fieldGroup: 23e4e445-4b38-4cb2-b804-8f0709fc5994
    handle: strength
    instructions: ''
    name: Strength
    searchable: true
    settings:
      decimals: 0
      defaultValue: '0'
      max: null
      min: '0'
      prefix: ''
      size: null
      suffix: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  4c46f78f-fc05-4610-b628-3401bc09e15d:
    contentColumnType: integer(10)
    fieldGroup: 23e4e445-4b38-4cb2-b804-8f0709fc5994
    handle: charLevel
    instructions: ''
    name: Level
    searchable: true
    settings:
      decimals: 0
      defaultValue: '1'
      max: null
      min: '0'
      prefix: ''
      size: null
      suffix: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  50a1e9a4-5f95-4f5c-8d74-201239c16d65:
    contentColumnType: integer(10)
    fieldGroup: 23e4e445-4b38-4cb2-b804-8f0709fc5994
    handle: wisdomModifier
    instructions: ''
    name: 'Wisdom Modifier'
    searchable: true
    settings:
      decimals: 0
      defaultValue: '0'
      max: null
      min: '-100'
      prefix: ''
      size: null
      suffix: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  58650e0c-dbb0-4416-a9f2-7e3e66d39b24:
    contentColumnType: integer(10)
    fieldGroup: 23e4e445-4b38-4cb2-b804-8f0709fc5994
    handle: constitutionModifier
    instructions: ''
    name: 'Constitution Modifier'
    searchable: true
    settings:
      decimals: 0
      defaultValue: '0'
      max: null
      min: '-100'
      prefix: ''
      size: null
      suffix: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  61786029-b796-465c-b1d8-fc7fc92082f7:
    contentColumnType: integer(10)
    fieldGroup: 23e4e445-4b38-4cb2-b804-8f0709fc5994
    handle: charisma
    instructions: ''
    name: Charisma
    searchable: true
    settings:
      decimals: 0
      defaultValue: '0'
      max: null
      min: '0'
      prefix: ''
      size: null
      suffix: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  6bde9132-4da1-44ca-be56-ad8a6a588dd1:
    contentColumnType: text
    fieldGroup: 23e4e445-4b38-4cb2-b804-8f0709fc5994
    handle: class
    instructions: ''
    name: Class
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7ba847b3-82a8-4806-9a22-27521e2a3b3c:
    contentColumnType: integer(10)
    fieldGroup: 23e4e445-4b38-4cb2-b804-8f0709fc5994
    handle: charismaModifier
    instructions: ''
    name: 'Charisma Modifier'
    searchable: true
    settings:
      decimals: 0
      defaultValue: '0'
      max: null
      min: '-100'
      prefix: ''
      size: null
      suffix: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  8614def5-7fbd-4ba4-8f14-f73be6102fc7:
    contentColumnType: text
    fieldGroup: 23e4e445-4b38-4cb2-b804-8f0709fc5994
    handle: alignment
    instructions: ''
    name: Alignment
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8a20aeca-3742-4f3f-9e47-c1fe5f9496f2:
    contentColumnType: integer(10)
    fieldGroup: 23e4e445-4b38-4cb2-b804-8f0709fc5994
    handle: exp
    instructions: ''
    name: Exp
    searchable: true
    settings:
      decimals: 0
      defaultValue: '0'
      max: null
      min: '0'
      prefix: ''
      size: null
      suffix: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  8d1596b9-1261-4320-af82-546ca10e72f0:
    contentColumnType: integer(10)
    fieldGroup: 23e4e445-4b38-4cb2-b804-8f0709fc5994
    handle: dexterity
    instructions: ''
    name: Dexterity
    searchable: true
    settings:
      decimals: 0
      defaultValue: '0'
      max: null
      min: '0'
      prefix: ''
      size: null
      suffix: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  b875d0a3-65f2-4668-8e5e-828cc1a5ae12:
    contentColumnType: integer(10)
    fieldGroup: 23e4e445-4b38-4cb2-b804-8f0709fc5994
    handle: intelligenceModifier
    instructions: ''
    name: 'Intelligence Modifier'
    searchable: true
    settings:
      decimals: 0
      defaultValue: '0'
      max: null
      min: '-100'
      prefix: ''
      size: null
      suffix: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  c60ac919-bcc2-4033-98db-c7b7ce052456:
    contentColumnType: integer(10)
    fieldGroup: 23e4e445-4b38-4cb2-b804-8f0709fc5994
    handle: constitution
    instructions: ''
    name: Constitution
    searchable: true
    settings:
      decimals: 0
      defaultValue: '0'
      max: null
      min: '0'
      prefix: ''
      size: null
      suffix: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  ce8c6d47-9591-4a57-a5a3-0abbc910a88a:
    contentColumnType: text
    fieldGroup: 23e4e445-4b38-4cb2-b804-8f0709fc5994
    handle: background
    instructions: ''
    name: Background
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f1885df5-1e09-44f0-891f-e4dd75f357de:
    contentColumnType: integer(10)
    fieldGroup: 23e4e445-4b38-4cb2-b804-8f0709fc5994
    handle: strengthModifier
    instructions: ''
    name: 'Strength Modifier'
    searchable: true
    settings:
      decimals: 0
      defaultValue: '0'
      max: null
      min: '-100'
      prefix: ''
      size: null
      suffix: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  fa80cda9-2c6f-4876-8ef5-6e14def438eb:
    contentColumnType: integer(10)
    fieldGroup: 23e4e445-4b38-4cb2-b804-8f0709fc5994
    handle: dexterityModifier
    instructions: ''
    name: 'Dexterity Modifier'
    searchable: true
    settings:
      decimals: 0
      defaultValue: '0'
      max: null
      min: '-100'
      prefix: ''
      size: null
      suffix: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
plugins:
  eager-beaver:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  imager:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
sections:
  3d51e8a8-b0d4-479a-88ac-01b9e5659ac9:
    enableVersioning: true
    entryTypes:
      9c583649-5619-4d3a-ad11-1ec1a5b7b2aa:
        fieldLayouts:
          b7c23a36-36bc-4787-aa60-c9b1610d9be8:
            tabs:
              -
                fields:
                  4c46f78f-fc05-4610-b628-3401bc09e15d:
                    required: false
                    sortOrder: 2
                  6bde9132-4da1-44ca-be56-ad8a6a588dd1:
                    required: false
                    sortOrder: 1
                  8614def5-7fbd-4ba4-8f14-f73be6102fc7:
                    required: false
                    sortOrder: 4
                  8a20aeca-3742-4f3f-9e47-c1fe5f9496f2:
                    required: false
                    sortOrder: 3
                  ce8c6d47-9591-4a57-a5a3-0abbc910a88a:
                    required: false
                    sortOrder: 5
                name: Details
                sortOrder: 1
              -
                fields:
                  224fd7cd-0613-42ac-8082-1700a37171a4:
                    required: false
                    sortOrder: 9
                  28c16db0-e3bc-43e3-abda-655cb84246f5:
                    required: false
                    sortOrder: 7
                  43da4518-b607-4804-a699-523220069c18:
                    required: false
                    sortOrder: 1
                  50a1e9a4-5f95-4f5c-8d74-201239c16d65:
                    required: false
                    sortOrder: 10
                  58650e0c-dbb0-4416-a9f2-7e3e66d39b24:
                    required: false
                    sortOrder: 6
                  61786029-b796-465c-b1d8-fc7fc92082f7:
                    required: false
                    sortOrder: 11
                  7ba847b3-82a8-4806-9a22-27521e2a3b3c:
                    required: false
                    sortOrder: 12
                  8d1596b9-1261-4320-af82-546ca10e72f0:
                    required: false
                    sortOrder: 3
                  b875d0a3-65f2-4668-8e5e-828cc1a5ae12:
                    required: false
                    sortOrder: 8
                  c60ac919-bcc2-4033-98db-c7b7ce052456:
                    required: false
                    sortOrder: 5
                  f1885df5-1e09-44f0-891f-e4dd75f357de:
                    required: false
                    sortOrder: 2
                  fa80cda9-2c6f-4876-8ef5-6e14def438eb:
                    required: false
                    sortOrder: 4
                name: Abilities
                sortOrder: 2
        handle: characters
        hasTitleField: true
        name: Characters
        sortOrder: 1
        titleFormat: ''
        titleLabel: Name
    handle: characters
    name: Characters
    propagationMethod: all
    siteSettings:
      3253961c-40ff-4967-bda7-42b923305ae9:
        enabledByDefault: true
        hasUrls: true
        template: ''
        uriFormat: 'character/{slug}'
    type: channel
siteGroups:
  84de28f8-ac64-4668-b1e5-690daa13fd61:
    name: Boilerplate
sites:
  3253961c-40ff-4967-bda7-42b923305ae9:
    baseUrl: '@rootUrl'
    handle: default
    hasUrls: true
    language: en-US
    name: Boilerplate
    primary: true
    siteGroup: 84de28f8-ac64-4668-b1e5-690daa13fd61
    sortOrder: 1
system:
  edition: pro
  live: true
  name: Boilerplate
  schemaVersion: 3.4.10
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  fieldLayouts:
    30924088-a462-4c79-9173-870b48c4299a:
      tabs:
        -
          name: Common
          sortOrder: 1
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
